# Welcome to Jekyll!
#

# Site settings
title: Nicolas Pettican Perez
description: |
  Data and life scientist,
  entrepreneur, programmer
  and fitness enthusiast.
owner: Nicolas Pettican Perez
first_published: 2016
email: nicolaspettican@gmail.com
url: "http://nicolaspettican.com"
social:
  #email: mailto:nicolaspettican@gmail.com
  twitter: https://twitter.com/PettiTweets
  github: https://github.com/nickpettican
  linkedin-square: https://linkedin.com/in/nickpettican
  facebook-official: https://facebook.com/nicolas.pettican
  google-plus-square: https://plus.google.com/u/0/nickpettican
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #slack:
  #vine:

# Build settings
markdown: kramdown
# permalink: pretty
#sass:
#  style: compressed
